#!/bin/bash
# Generate Secrets.generated.swift with obfuscated OAuth credentials
# Sources: fnox (local dev), GitHub Secrets (CI), or env vars
set -e

OUTPUT="Projects/ExFigStudio/Sources/Generated/Secrets.generated.swift"
mkdir -p "$(dirname "$OUTPUT")"

# Load secrets via fnox if available
if command -v fnox &> /dev/null && [ -f "fnox.toml" ]; then
    eval "$(fnox env 2>/dev/null || true)"
fi

# Check if credentials are set
if [ -z "$FIGMA_CLIENT_ID" ] || [ -z "$FIGMA_CLIENT_SECRET" ]; then
    echo "OAuth credentials not configured"
    echo "   Run: fnox set FIGMA_CLIENT_ID"
    echo "   Run: fnox set FIGMA_CLIENT_SECRET"
    echo "   Or set FIGMA_CLIENT_ID and FIGMA_CLIENT_SECRET env vars"
    echo ""
    echo "Generating with empty values (Personal Token will still work)"
    FIGMA_CLIENT_ID=""
    FIGMA_CLIENT_SECRET=""
fi

cat > "$OUTPUT" << EOF
// Auto-generated by Scripts/generate-secrets.sh
// DO NOT EDIT - configure via fnox or GitHub Secrets

import Foundation
import ObfuscateMacro

enum Secrets {
    static let figmaClientId = #ObfuscatedString("${FIGMA_CLIENT_ID}")
    static let figmaClientSecret = #ObfuscatedString("${FIGMA_CLIENT_SECRET}")

    static var isOAuthConfigured: Bool {
        !figmaClientId.isEmpty && !figmaClientSecret.isEmpty
    }
}
EOF

echo "Generated $OUTPUT"
